[pytest]
testpaths = tests
pythonpath = .
asyncio_mode = auto
filterwarnings =
	ignore:The 'app' shortcut is now deprecated. Use the explicit style 'transport=WSGITransport(app=...)' instead.:DeprecationWarning
	ignore:The configuration option "asyncio_default_fixture_loop_scope" is unset.:DeprecationWarning


